### ISSUE TITLE
Wheres the source code? is this a save.dat stealer?

### ISSUE THREAD

**Issue by bacontsu** [bacontsu/multibox#1]
Sorry, the source code wouldn't be available for public. I've learned something about gabb's status rn. And no its not a save.dat stealer, keylogger, or a rats. even I try to re-write anything that's seems suspicious from the base source code.

**Comment by bacontsu** [comment]
the main idea of I making this is to make a more efficient multiboxer/autofarmer than Gabb itself, which is bloated a lot. and now more bloated because of all the rats and stealer people put inside.

**Comment by Mir-2002** [comment]
How would we know if it isnt a stealer if we cant scan the source code itself?

**Comment by bacontsu** [comment]
> How would we know if it isnt a stealer if we cant scan the source code itself?

you can look up at the task manager that this program doesn't use so much cpu usage, unlike gabb that somehow use a high cpu usage even when idle.

Also I've checked VirusTotal and you can also check it by yourself, here's the link:
https://www.virustotal.com/gui/url/c8faae3d8246125a7259f3d4b0f534511cf61ad4674458004b4869ac7f6dddf8/detection

I know virustotal isn't very accurate, but atleast it doesn't show any stealer behaviour.

But since this thing uses https://github.com/rvknth043/Global-Low-Level-Key-Board-And-Mouse-Hook 
it alr has a bad history of eating performances on lower end hardware (atleast better than gabb multiboxing)

tested on those processors with 8 bots :
AMD A8-7410 - 4c 4t
intel Pentium G2020 - 2c 2t
intel Core i3 3240 - 2c 4t
intel Core i3 4150 - 2c 4t

that its kinda struggles with A8 and Pentium, because they're low end hardware, but better performance compared than gabb (also tested on those processor) at the time.

**Comment by bacontsu** [comment]
fully open source now, if you can fix something make a pull request
