### ISSUE TITLE
ITS A FUCKING VIRUS, EVEN MALWAREBYTES DETECTED IT. FUCK YOU BACONTSU

### ISSUE THREAD

**Issue by lel123lel** [bacontsu/multibox#4]
heres proof lmao.
https://www.virustotal.com/gui/file/041990ea7aa758a669c449b7195fd11714f2a597824d1eb91512d872a0a0807c/detection

**Comment by lel123lel** [comment]
i reported this shit. pls get off internet motherfucker

**Comment by bacontsu** [comment]
either you lying with fake file, or i dont know anymore. i checked with virustotal straight to the link of my github and it doesnt detect anything. 

did you desperately need the source code? doing all of this? i can even release the source code right now to prove you wrong. but thats gonna make you win.

im not gonna fall for this trick, i can even do 'full' documentation about the code. what about you check blacklock's one before saying anything?

**Comment by bacontsu** [comment]
u know what i didnt even bother with this shit anymore, imma upload the source code as soon as i fixed my pc. im tired of this shit.
