### ISSUE TITLE
FAKE?? WHAT FAKE? HOW TF AM I GONNA FAKE THAT ANYWAY?

### ISSUE THREAD

**Issue by lel123lel** [bacontsu/multibox#5]
https://www.virustotal.com/gui/url/c8faae3d8246125a7259f3d4b0f534511cf61ad4674458004b4869ac7f6dddf8/detection
this virustotal link you sent is a fucking scam. ofc its gonna say "clean" cuz what u put is the fucking URL. get that? U.R.L!!
and mine isnt, i downloaded the file on a virtual box and sent it in virustotal, and whaddya know, a million antivirus picked it up. so release the god damn source if you wanna prove that this isnt some virus shit.

**Comment by lel123lel** [comment]
url xDDDD
![image](https://user-images.githubusercontent.com/73583518/113477271-44d81200-94b3-11eb-869e-099c1dda220d.png)

**Comment by bacontsu** [comment]
aight first of all let me get it straight, im sorry for the rude replies i made before, i have a really bad day today my pc wont stop from a bsod loop. and i shouldnt make false accusation, etc.

it turns out that the hooks are doing something sketchy. I dont actually know how it works since im using someone's hook, and every hook would do that (kinda), for example the hooks that were used on osiris. i CAN release the source code until i got my pc fixed, search it as you like. i've been trying to fix this trojan thing for a long time ago. actually i will be very helped if you or anybody could find any sketchy thing inside my program and help me remove/fix it. also looks up blacklock's source code 
github.com/blacklock/gtautofarmer
so you can check anything to compare it to mine

**Comment by bacontsu** [comment]
> https://www.virustotal.com/gui/url/c8faae3d8246125a7259f3d4b0f534511cf61ad4674458004b4869ac7f6dddf8/detection
> this virustotal link you sent is a fucking scam. ofc its gonna say "clean" cuz what u put is the fucking URL. get that? U.R.L!!
> and mine isnt, i downloaded the file on a virtual box and sent it in virustotal, and whaddya know, a million antivirus picked it up. so release the god damn source if you wanna prove that this isnt some virus shit.

also its not a scam. its a direct link to my file, virustotal bot would instantly download it an checks the file. i dont even know why it doesnt detects it using direct url download. not me making up stuff.

**Comment by lel123lel** [comment]
uh no virustotal doesnt do that. sometimes websites can have viruses, i dunno why but it happens. thats why virustotal lets u put a url but github is clean, it is a trusted website, even if you put the direct download link url. its just gonna check that url and not download the file. you have to download the file and upload it urself to see if it a virus or nah.

**Comment by bacontsu** [comment]
> uh no virustotal doesnt do that. sometimes websites can have viruses, i dunno why but it happens. thats why virustotal lets u put a url but github is clean, it is a trusted website, even if you put the direct download link url. its just gonna check that url and not download the file. you have to download the file and upload it urself to see if it a virus or nah.

oh nevermind. im pretty sorry about that, i might very misunderstood the use of virustotal url. also just got my pc working so i might upload it pretty soon. thanks for the help

**Comment by bacontsu** [comment]
kinda fixed my pc atm, the source code has been uploaded. please take a look at it

**Comment by imtrynalearn** [comment]
delete obj folder and bin folder and viruses are gone

**Comment by imtrynalearn** [comment]
nvm i compiled and the .exe contains viruses lol

**Comment by bacontsu** [comment]
> nvm i compiled and the .exe contains viruses lol

its a hooking methods lmao of course it will get false trigger. its literally OPEN SOURCE you can see things inside

**Comment by bacontsu** [comment]
> nvm i compiled and the .exe contains viruses lol

further more research into the code i find out that the only thing that makes this as a virus is the ```File.Exist()``` function lmao 
its actually a code to search for growtopia
```set {
				if (File.Exists(value)) {
					_growtopiaPath = value;
					fileSelectDialog.InitialDirectory = _growtopiaPath;
					fileNameDisplayer.Text = _growtopiaPath;
				} else {
					MessageBox.Show("Incorrect file specified", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
```
					
might try to change it using try catch later idk 



EDIT :
replaced the ```File.Exists()``` function to ```_growtopiaPath.Contains("Growtopia.exe")``` but for some reason it still false flagged, i even removed the whole keyboard/mouse hook
```
                                  if (_growtopiaPath.Contains("Growtopia.exe")) {
					_growtopiaPath = value;
					fileSelectDialog.InitialDirectory = _growtopiaPath;
					fileNameDisplayer.Text = _growtopiaPath;
				} else {
					MessageBox.Show("Incorrect file specified", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
				}
				
```

EDIT 2 : yes its the hooking methods i guess
