### ISSUE TITLE
Doesn't even work

### ISSUE THREAD

**Issue by 00due** [bacontsu/multibox#6]
I compiled it using vs 2019, ran it and I get the same error as in blacklock's program every time I try to open multiple windows.

**Comment by bacontsu** [comment]
> I compiled it using vs 2019, ran it and I get the same error as in blacklock's program every time I try to open multiple windows.

you had to open it as administrator, windows wont allow you to open multiple windows if you dont have administrator access because it 'bypassing' growtopia's anti multiple client system.
